global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 192.168.0.179:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "192.168.0.179:9090"

  - job_name: "node-exporter"
    static_configs:
      - targets:
        - "192.168.0.179:9100"

  - job_name: "cadvisor"
    static_configs:
      - targets:
        - "192.168.0.179:8080"

  - job_name: "windows"
    static_configs:
      - targets:
        - "192.168.0.183:9182"

  - job_name: "ubuntu"
    static_configs:
      - targets:
        - "192.168.0.101:9100"

  - job_name: "mikrotik"
    static_configs:
      - targets:
        - 192.168.0.100
    metrics_path: /snmp
    params:
      module: [mikrotik]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.0.143:9116

