route:
  receiver: 'telegram'
  routes:    
  # All alerts with severity=warning or severity=critical
  # are dispatched to the telegram receiver.
  - receiver: 'telegram'
    group_wait: 10s
    matchers:
    - severity=~"warning|critical|firing"

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: "6503640997:AAHgBIhBADWPVK0IcImAOuV7N9URf1HyUuk"
    chat_id: -1001788626394
